version: 0.2

env:
  variables:
    AWS_REGION: "eu-west-2"

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements_test.txt
  build:
    commands:
      - echo Lint phase...
      - isort *.py **/*.py
      - black --skip-string-normalization *.py **/*.py
      - flake8 --ignore=E501,W503,BLK100 --per-file-ignores=**/__init__.py:F401 *.py **/*.py

      - echo Tests phase...
      - python -m unittest discover -s tests
