branch-defaults:
  develop:
    environment: serviceName-staging
environment-defaults:
  serviceName-staging:
    branch: null
    repository: null
global:
  application_name: serviceName
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
